# Generated by Django 5.0.6 on 2026-02-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'admin'), ('HOSPITAL', 'hospital'), ('UNIVERSITY', 'university')], max_length=10, null=True),
        ),
    ]
